sections = {    'section1' : 'SOCIAL AND DEMOGRAPHIC INDICATORS',
                'section2' : 'HEALTH',
                'section3' : 'STATE DOMESTIC PRODUCT',
                'section4' : 'AGRICULTURE AND ALLIED',
                'section5' : 'ENVIRONMENT',
                'section6' : 'PRICE AND WAGES',
                'section7' : 'INDUSTRY',
                'section8' : 'INFRASTRUCTURE',
                'section9' : 'BANKING',
                'section10': 'FISCAL',
            }


group_names = {
    'section1':
    {
        'table1' : 'Table 1: State-wise Total Population',
        'table2' : 'Table 2: State-wise Population in Rural Area',
        'table3' : 'Table 3: State-wise Population in Urban Area',
        'table4' : 'Table 4: State-wise Decadal Growth Rate of Population',
        'table5' : 'Table 5: State-wise Sex Ratio',
        'table6' : 'Table 6: State-wise Literacy Rate',
        'table7' : 'Table 7: State- wise Gross Enrolment Ratio',
        'table8' : 'Table 8: State-wise Density of Population',
        'table9' : 'Table 9: State-wise Birth Rate',
        'table10': 'Table 10: State-wise Death Rate',
        'table11': 'Table 11: State-wise Infant Mortality Rate',
        'table12': 'Table 12: State-wise Maternal Mortality Ratio',
        'table13': 'Table 13: State-wise Total Fertility Rate',
        'table14': 'Table 14: State-wise Life Expectancy',
        'table15': 'Table 15: State-wise Unemployment Rate: Usual Status (Adjusted) (Rural)',
        'table16': 'Table 16: State-wise Unemployment Rate: Usual Status (Adjusted) (Urban)',
        'table17': 'Table 17: State-wise Poverty Rate',
        'table18': 'Table 18: State-wise Population Estimates- Multi-dimensional Poverty Index',
        'table19': 'Table 19: State-wise Natural Population Growth Rate',
            },
    'section2':
    {
        'table20': 'Table 20: State-wise Children Aged 6-59 Months Who are Anaemic',
        'table21': 'Table 21: State-wise Pregnant Women Aged 15-49 Years Who are Anaemic',
        'table22': 'Table 22: State-wise Health Infrastructure \u2013 Doctors and Specialists',
        'table23': 'Table 23: State-wise Number of Government Hospitals',
        'table24': 'Table 24: State-wise Public Expenditure on Health',
            },
    'section3':
    {
        'table25': 'Table 25: Per Capita Net State Domestic Product (Current Prices)',
        'table26': 'Table 26: Per Capita Net State Domestic Product (Constant Prices)',
        'table27': 'Table 27: Gross State Domestic Product (Current Prices)',
        'table28': 'Table 28: Gross State Domestic Product (Constant Prices)',
        'table29': 'Table 29: Net State Domestic Product (Current Prices)',
        'table30': 'Table 30: Net State Domestic Product (Constant Prices)',
        'table31': 'Table 31: Gross State Value Added by Economic Activity - Agriculture (Current Prices)',
        'table32': 'Table 32: Gross State Value Added by Economic Activity - Agriculture (Constant Prices)',
        'table33': 'Table 33: Net State Value Added by Economic Activity - Agriculture (Current Prices)',
        'table34': 'Table 34: Net State Value Added by Economic Activity - Agriculture (Constant Prices)',
        'table35': 'Table 35: Gross State Value Added by Economic Activity - Manufacturing (Current Prices)',
        'table36': 'Table 36: Gross State Value Added by Economic Activity - Manufacturing (Constant Prices)',
        'table37': 'Table 37: Net State Value Added by Economic Activity - Manufacturing (Current Prices)',
        'table38': 'Table 38: Net State Value Added by Economic Activity - Manufacturing (Constant Prices)',
        'table39': 'Table 39: Gross State Value Added by Economic Activity - Construction (Current Prices)',
        'table40': 'Table 40: Gross State Value Added by Economic Activity - Construction (Constant Prices)',
        'table41': 'Table 41: Net State Value Added by Economic Activity - Construction (Current Prices)',
        'table42': 'Table 42: Net State Value Added by Economic Activity - Construction (Constant Prices)',
        'table43': 'Table 43: Gross State Value Added by Economic Activity - Industry (Current Prices)',
        'table44': 'Table 44: Gross State Value Added by Economic Activity - Industry (Constant Prices)',
        'table45': 'Table 45: Net State Value Added by Economic Activity - Industry (Current Prices)',
        'table46': 'Table 46: Net State Value Added by Economic Activity - Industry (Constant Prices)',
        'table47': 'Table 47: Gross State Value Added by Economic Activity - Banking and Insurance (Current Prices)',
        'table48': 'Table 48: Gross State Value Added by Economic Activity - Banking and Insurance (Constant Prices)',
        'table49': 'Table 49: Net State Value Added by Economic Activity - Banking and Insurance (Current Prices)',
        'table50': 'Table 50: Net State Value Added by Economic Activity - Banking and Insurance (Constant Prices)',
        'table51': 'Table 51: Gross State Value Added by Economic Activity - Services (Current Prices)',
        'table52': 'Table 52: Gross State Value Added by Economic Activity - Services (Constant Prices)',
        'table53': 'Table 53: Net State Value Added by Economic Activity - Services (Current Prices)',
        'table54': 'Table 54: Net State Value Added by Economic Activity - Services (Constant Prices)',
        },
    'section4':
    {
        'table55': 'Table 55: State-wise Pattern of Land Use - Gross Sown Area',
        'table56': 'Table 56: State-wise Pattern of Land Use- Net Sown Area',
        'table57': 'Table 57: State-wise Pattern of Land Use - Gross Irrigated Area',
        'table58': 'Table 58: State-wise Pattern of Land Use - Net Irrigated Area',
        'table59': 'Table 59: State-wise Pattern of Land Use - Cropping Intensity',
        'table60': 'Table 60: State-wise Production of Foodgrains - Rice',
        'table61': 'Table 61: State-wise Production of Foodgrains - Wheat',
        'table62': 'Table 62: State-wise Production of Foodgrains - Coarse Cereals',
        'table63': 'Table 63: State-wise Production of Foodgrains - Pulses',
        'table64': 'Table 64: State-wise Production of Total Foodgrains',
        'table65': 'Table 65: State-wise Production of Non-Foodgrains - Oilseeds',
        'table66': 'Table 66: State-wise Production of Non-Foodgrains - Cotton (Lintt)',
        'table67': 'Table 67: State-wise Production of Non-Foodgrains - Sugarcane',
        'table68': 'Table 68: State-wise Production of Non-Foodgrains - Raw Jute & Mesta',
        'table69': 'Table 69: State-wise Area of Foodgrains - Rice',
        'table70': 'Table 70: State-wise Area of Foodgrains - Wheat',
        'table71': 'Table 71: State-wise Area of Foodgrains - Coarse Cereals',
        'table72': 'Table 72: State-wise Area of Foodgrains - Pulses',
        'table73': 'Table 73: State-wise Area of Total Foodgrains',
        'table74': 'Table 74: State-wise Area of Total Fruits',
        'table75': 'Table 75: State-wise Area of Total Vegetables',
        'table76': 'Table 76: State-wise Production of Total Fruits',
        'table77': 'Table 77: State-wise Production of Total Vegetables',
        'table78': 'Table 78: State-wise Area of Non-Foodgrains - Oilseeds',
        'table79': 'Table 79: State-wise Area of Non-Foodgrains - Cotton (Lintt)',
        'table80': 'Table 80: State-wise Area of Non-Foodgrains - Sugarcane',
        'table81': 'Table 81: State-wise Area of Non-Foodgrains - Raw Jute & Mesta',
        'table82': 'Table 82: State-wise Estimates of Yield - Rice',
        'table83': 'Table 83: State-wise Estimates of Yield - Wheat',
        'table84': 'Table 84: State-wise Estimates of Yield - Coarse Cereals',
        'table85': 'Table 85: State-wise Estimates of Yield - Pulses',
        'table86': 'Table 86: State-wise Estimates of Yield - Total Foodgrains',
        'table87': 'Table 87: State-wise Estimates of Yield - Oilseeds',
        'table88': 'Table 88: State-wise Estimates of Yield - Cotton (Lintt)',
        'table89': 'Table 89: State-wise Estimates of Yield - Sugarcane',
        'table90': 'Table 90: State-wise Estimates of Yield - Raw Jute & Mesta',
        'table91': 'Table 91: State-wise Per Hectare Consumption of Fertiliser (N+P+K)',
        'table92': 'Table 92: State-wise Meat Production',
        'table93': 'Table 93: State-wise Milk Production',
        'table94': 'Table 94: State-wise Egg Production',
        'table95': 'Table 95: State-wise Fish Production',
        'table96': 'Table 96: State-wise Wool Production',
        'table97': 'Table 97: State-wise RIDF Sanction and Disbursements',
        'table98': 'Table 98: State-wise Storage Capacity of Foodgrains',
        'table99': 'Table 99: Storage Capacity for Foodgrains and Utilisation under FCI',
       'table100': 'Table 100: State-wise Cold Storage Capacity',
        },
    'section5':
    {
        'table101': 'Table 101: State-wise Forest Cover',
        'table102': 'Table 102: State-wise Tree Cover',
        'table103': 'Table 103: Sub-Division-Wise Annual Rainfall',
        'table104': 'Table 104: State-wise Expenditure on Relief on Natural Calamities',
        'table105': 'Table 105: State-wise Sustainable Development Goals (SDGs) Score',
        },
    'section6':
        {
        'table106': 'Table 106: State-wise Average Inflation (CPI) - General',
        'table107': 'Table 107: State-wise Average Inflation (CPI) - Food and Beverages',
        'table108': 'Table 108: State-wise Average Inflation (CPI) - Fuel and Light',
        'table109': 'Table 109: State-wise Average Inflation (CPI) - Housing (Urban)',
        'table110': 'Table 110: State-wise Average Daily Wage Rates in Rural India (Men - Construction Workers)',
        'table111': 'Table 111: State-wise Average Daily Wage Rates in Rural India (Men - General Agricultural Labourers)',
        'table112': 'Table 112: State-wise Average Daily Wage Rates in Rural India (Men - Horticulture Workers)',
        'table113': 'Table 113: State-wise Average Daily Wage Rates in Rural India (Men - Non-Agricultural Labourers)',
        },
   'section7':
       {
        'table114': 'Table 114: State-wise Number of Factories',
        'table115': 'Table 115: State-wise Fixed Capital',
        'table116': 'Table 116: State-wise Working Capital',
        'table117': 'Table 117: State-wise Physical Working Capital',
        'table118': 'Table 118: State-wise Productive Capital',
        'table119': 'Table 119: State-wise Invested Capital',
        'table120': 'Table 120: State-wise Number of Workers',
        'table121': 'Table 121: State-wise Total Persons Engaged',
        'table122': 'Table 122: State-wise Total Emoluments',
        'table123': 'Table 123: State-wise Total Input',
        'table124': 'Table 124: State-wise Value of Gross Output',
        'table125': 'Table 125: State-wise Net Value Added',
        'table126': 'Table 126: State-wise Gross Value Added',
        'table127': 'Table 127: State-wise Net Fixed Capital Formation',
        'table128': 'Table 128: State-wise Gross Fixed Capital Formation',
        'table129': 'Table 129: State-wise Gross Capital Formation',
        'table130': 'Table 130: State-wise Number of Employees',
        'table131': 'Table 131: State-wise Number of Mandays - Employees',
        'table132': 'Table 132: State-wise Medium & Small Scale Industries - Total Number of Units',
        'table133': 'Table 133: State-wise Medium & Small Scale Industries - Total Investments',
        'table134': 'Table 134: State-wise Medium & Small Scale Industries - Total Production',
        'table135': 'Table 135: State-wise Medium & Small Scale Industries - Total Employment',
        },
   'section8':
    {
        'table136': 'Table 136: State-wise Per Capita Availability of Power',
        'table137': 'Table 137: State-wise Availability of Power',
        'table138': 'Table 138: State-wise Installed Capacity of Power',
        'table139': 'Table 139: State-wise Power Requirement',
        'table140': 'Table 140: State-wise Total Installed Capacity of Grid Interactive Renewable Power',
        'table141': 'Table 141: State-wise Length of National Highways',
        'table142': 'Table 142: State-wise Railway Route',
        'table143': 'Table 143: State-wise Length of Roads',
        'table144': 'Table 144: State-wise Length of State Highways',
        'table145': 'Table 145: State-wise Ease of Doing Business Rank',
        'table146': 'Table 146: State-wise Electricity Transmission & Distribution Losses',
        'table147': 'Table 147: State-wise Telephones per 100 Population',
        'table148': 'Table 148: State-wise Road Constructed under PMGSY',
        },
   'section9':
       {
        'table149': 'Table 149: State-wise Distribution of Offices of Scheduled Commercial Banks',
        'table150': 'Table 150: State-wise Credit-Deposit Ratio of Scheduled Commercial Banks - According to Place of Sanction',
        'table151': 'Table 151: State-wise Credit-Deposit Ratio of Scheduled Commercial Banks - According to Place of Utilisation',
        'table152': 'Table 152: State-wise Deposits by Scheduled Commercial Banks in India',
        'table153': 'Table 153: State-wise Credit by Scheduled Commercial Banks in India',
        'table154': 'Table 154: State-wise Credit to Agriculture by Scheduled Commercial Banks',
        'table155': 'Table 155: State-wise Credit to Industry by Scheduled Commercial Banks',
        'table156': 'Table 156: State-wise Personal Loans by Scheduled Commercial Banks',
        'table157': 'Table 157: State-wise Deposits of Regional Rural Banks',
        'table158': 'Table 158: State-wise Credit of Regional Rural Banks',
        'table159': 'Table 159: State-wise Credit-Deposit Ratio of Regional Rural Banks',
        'table160': 'Table 160: State-wise Number of Branches of Regional Rural Banks',
        },
   'section10':
       {
        'table161': 'Table 161: State-wise Gross Fiscal Deficit',
        'table162': 'Table 162: State-wise Revenue Deficit',
        'table163': 'Table 163: State-wise Primary Deficit',
        'table164': 'Table 164: State-wise Own Tax Revenue',
        'table165': 'Table 165: State-wise Own Non-Tax Revenue',
        'table166': 'Table 166: State-wise Interest Payments',
        'table167': 'Table 167: State-wise Pension',
        'table168': 'Table 168: State-wise Capital Expenditure',
        'table169': 'Table 169: State-wise Capital Outlay',
        'table170': 'Table 170: State-wise Social Sector Expenditure',
        'table171': 'Table 171: State-wise Composition of Outstanding Liabilities',
        'table172': 'Table 172: State-wise Outstanding Guarantees of State Governments',
        }
}

do_not_read = {
    'section1': ['table4', 'table7', 'table14'],
    'section2': ['table22', 'table23'],
        }
#TODO New format needed for 'SOCIAL AND DEMOGRAPHIC INDICATORS', 'Table 14:'

# 1960 - Bombay state split into Maharashtra and Gujarat
# 1963 - Nagaland carved out of Assam
# 1966 - Haryana and Himachal Pradesh carved out of Punjab state
# 1972 - Meghalaya , Manipur and Tripura were formed
# 1975 - Sikkim became part of Indian union
# 1987 - Goa and Arunachal Pradesh became states (earlier these were UTs)
# 2000 - Uttaranchal (out of UP), Jharkhand (out of Bihar) and Chhattisgarh (out of Madhya Pradesh) were formed
# Telangana (out of Andhra Pradesh), when it was eventually created in 2014, became India's 29th state.

state_change = {
    'Telangana': 'Andhra Pradesh',
            }

plotting_info = {
    ('section1', 'table1', ''):  {'TITLE': 'Total Population'},
    ('section1', 'table2', ''):  {'TITLE': 'Population in Rural Area'},
    ('section1', 'table3', ''):  {'TITLE': 'Population in Urban Area'},
    ('section1', 'table5', ''):  {'TITLE': 'Sex Ratio'},
    ('section1', 'table6', ''):  {'TITLE': 'Literacy Rate'},
    ('section1', 'table8', ''):  {'TITLE': 'Population Density'},
    ('section1', 'table9', ''):  {'TITLE': 'Birth Rate'},
    ('section1', 'table10', ''): {'TITLE': 'Death Rate'},
    ('section1', 'table11', ''): {'TITLE': 'Infant Mortality Rate'},
    ('section1', 'table12', ''): {'TITLE': 'Maternal Mortality Ratio'},
    ('section1', 'table13', ''): {'TITLE': 'Fertility Rate'},
    ('section1', 'table15', 'Rural Male'):     {'TITLE': 'Unemployment Rate Rural Male'},
    ('section1', 'table15', 'Rural Female'):   {'TITLE': 'Unemployment Rate Rural Female'},
    ('section1', 'table15', 'Rural Overall'):  {'TITLE': 'Unemployment Rate Rural Overall'},
    ('section1', 'table16', 'Urban Male'):     {'TITLE': 'Unemployment Rate Urban Male'},
    ('section1', 'table16', 'Urban Female'):   {'TITLE': 'Unemployment Rate Urban Female'},
    ('section1', 'table16', 'Urban Overall'):  {'TITLE': 'Unemployment Rate Urban Overall'},
    ('section1', 'table17', 'No. of Persons'): {'TITLE': 'Poverty Rate  No. of Persons'},
    ('section1', 'table17', 'Percentage'):     {'TITLE': 'Poverty Rate  Percentage'},
    ('section1', 'table18', 'Headcount Ratio'): {'TITLE': 'Multi-Dimensional Poverty Headcount Ratio'},
    ('section1', 'table18', 'Intensity'):      {'TITLE': 'Multi-Dimensional Poverty Intensity'},
    ('section1', 'table18', 'MPI'):            {'TITLE': 'Multi-Dimensional Poverty MPI'},
    ('section1', 'table19', 'Total'):          {'TITLE': 'Natural Population Growth Rate Total'},
    ('section1', 'table19', 'Rural'):          {'TITLE': 'Natural Population Growth Rate Rural'},
    ('section1', 'table19', 'Urban'):          {'TITLE': 'Natural Population Growth Rate Urban'},

    ('section2', 'table20', ''): {'TITLE': 'Anaemic Children 6-59 Months'},
    ('section2', 'table21', ''): {'TITLE': 'Anaemic Pregnant Women 15-49 Years'},
    ('section2', 'table24', ''): {'TITLE': 'Public Expenditure on Health'},

    ('section3', 'table25', 'Base_2004-05'): {'TITLE': 'Net SDP Per Capita (Current Prices) (BASE:2004-05)', 'ADDABLE': False},
    ('section3', 'table25', 'Base_2011-12'): {'TITLE': 'Net SDP Per Capita (Current Prices) (BASE:2011-12)', 'ADDABLE': False},
    ('section3', 'table26', 'Base_2004-05'): {'TITLE': 'Net SDP Per Capita (Constant Prices) (BASE:2004-05)', 'ADDABLE': False},
    ('section3', 'table26', 'Base_2011-12'): {'TITLE': 'Net SDP Per Capita (Constant Prices) (BASE:2011-12)', 'ADDABLE': False},
    ('section3', 'table27', 'Base_2004-05'): {'TITLE': 'Gross SDP(Current Prices) (BASE:2004-05)'},
    ('section3', 'table27', 'Base_2011-12'): {'TITLE': 'Gross SDP(Current Prices) (Base:2011-12)'},
    ('section3', 'table28', 'Base_2004-05'): {'TITLE': 'Gross SDP(Constant Prices) (BASE:2004-05)'},
    ('section3', 'table28', 'Base_2011-12'): {'TITLE': 'Gross SDP(Constant Prices) (Base:2011-12)'},
    ('section3', 'table29', 'Base_2004-05'): {'TITLE': 'Net SDP (Current Prices) (BASE:2004-05)'},
    ('section3', 'table29', 'Base_2011-12'): {'TITLE': 'Net SDP (Current Prices) (BASE:2011-12)'},
    ('section3', 'table30', 'Base_2004-05'): {'TITLE': 'Net SDP (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table30', 'Base_2011-12'): {'TITLE': 'Net SDP (Constant Prices) (BASE:2011-12)'},
    ('section3', 'table31', 'Base_2004-05'): {'TITLE': 'Gross Agriculture Value Add (Current Prices) (BASE:2004-05)'},
    ('section3', 'table31', 'Base_2011-12'): {'TITLE': 'Gross Agriculture Value Add (Current Prices) (BASE:2011-12)'},
    ('section3', 'table32', 'Base_2004-05'): {'TITLE': 'Gross Agriculture Value Add (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table32', 'Base_2011-12'): {'TITLE': 'Gross Agriculture Value Add (Constant Prices) (BASE:2011-12)'},
    ('section3', 'table33', 'Base_2004-05'): {'TITLE': 'Net Agriculture Value Add (Current Prices) (BASE:2004-05)'},
    ('section3', 'table33', 'Base_2011-12'): {'TITLE': 'Net Agriculture Value Add (Current Prices) (BASE:2011-12)'},
    ('section3', 'table34', 'Base_2004-05'): {'TITLE': 'Net Agriculture Value Add (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table34', 'Base_2011-12'): {'TITLE': 'Net Agriculture Value Add (Constant Prices) (BASE:2011-12)'},
    ('section3', 'table35', 'Base_2011-12'): {'TITLE': 'Gross Manufacturing Value Add (Current Prices) (BASE:2004-05)'},
    ('section3', 'table35', 'Base_2011-12'): {'TITLE': 'Gross Manufacturing Value Add (Current Prices) (BASE:2011-12)'},
    ('section3', 'table36', 'Base_2011-12'): {'TITLE': 'Gross Manufacturing Value Add (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table36', 'Base_2011-12'): {'TITLE': 'Gross Manufacturing Value Add (Constant Prices) (BASE:2011-12)'},
    ('section3', 'table37', 'Base_2011-12'): {'TITLE': 'Net Manufacturing Value Add (Current Prices) (BASE:2004-05)'},
    ('section3', 'table37', 'Base_2011-12'): {'TITLE': 'Net Manufacturing Value Add (Current Prices) (BASE:2011-12)'},
    ('section3', 'table38', 'Base_2011-12'): {'TITLE': 'Net Manufacturing Value Add (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table38', 'Base_2011-12'): {'TITLE': 'Net Manufacturing Value Add (Constant Prices) (BASE:2011-12)'},
    ('section3', 'table39', 'Base_2011-12'): {'TITLE': 'Gross Construction Value Add (Current Prices) (BASE:2004-05)'},
    ('section3', 'table39', 'Base_2011-12'): {'TITLE': 'Gross Construction Value Add (Current Prices) (BASE:2011-12)'},
    ('section3', 'table40', 'Base_2011-12'): {'TITLE': 'Gross Construction Value Add (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table40', 'Base_2011-12'): {'TITLE': 'Gross Construction Value Add (Constant Prices) (BASE:2011-12)'},
    ('section3', 'table41', 'Base_2011-12'): {'TITLE': 'Net Construction Value Add (Current Prices) (BASE:2004-05)'},
    ('section3', 'table41', 'Base_2011-12'): {'TITLE': 'Net Construction Value Add (Current Prices) (BASE:2011-12)'},
    ('section3', 'table42', 'Base_2011-12'): {'TITLE': 'Net Construction Value Add (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table42', 'Base_2011-12'): {'TITLE': 'Net Construction Value Add (Constant Prices) (BASE:2011-12)'},
    ('section3', 'table43', 'Base_2011-12'): {'TITLE': 'Gross Industry Value Add (Current Prices) (BASE:2004-05)'},
    ('section3', 'table43', 'Base_2011-12'): {'TITLE': 'Gross Industry Value Add (Current Prices) (BASE:2011-12)'},
    ('section3', 'table44', 'Base_2011-12'): {'TITLE': 'Gross Industry Value Add (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table44', 'Base_2011-12'): {'TITLE': 'Gross Industry Value Add (Constant Prices) (BASE:2011-12)'},
    ('section3', 'table45', 'Base_2011-12'): {'TITLE': 'Net Industry Value Add (Current Prices) (BASE:2004-05)'},
    ('section3', 'table45', 'Base_2011-12'): {'TITLE': 'Net Industry Value Add (Current Prices) (BASE:2011-12)'},
    ('section3', 'table46', 'Base_2011-12'): {'TITLE': 'Net Industry Value Add (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table46', 'Base_2011-12'): {'TITLE': 'Net Industry Value Add (Constant Prices) (BASE:2011-12)'},
    ('section3', 'table47', 'Base_2011-12'): {'TITLE': 'Gross Banking and Insurance Value Add (Current Prices) (BASE:2004-05)'},
    ('section3', 'table47', 'Base_2011-12'): {'TITLE': 'Gross Banking and Insurance Value Add (Current Prices) (BASE:2011-12)'},
    ('section3', 'table48', 'Base_2011-12'): {'TITLE': 'Gross Banking and Insurance Value Add (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table48', 'Base_2011-12'): {'TITLE': 'Gross Banking and Insurance Value Add (Constant Prices) (BASE:2011-12)'},
    ('section3', 'table49', 'Base_2011-12'): {'TITLE': 'Net Banking and Insurance Value Add (Current Prices) (BASE:2004-05)'},
    ('section3', 'table49', 'Base_2011-12'): {'TITLE': 'Net Banking and Insurance Value Add (Current Prices) (BASE:2011-12)'},
    ('section3', 'table50', 'Base_2011-12'): {'TITLE': 'Net Banking and Insurance Value Add (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table50', 'Base_2011-12'): {'TITLE': 'Net Banking and Insurance Value Add (Constant Prices) (BASE:2011-12)'},
    ('section3', 'table51', 'Base_2011-12'): {'TITLE': 'Gross Services Value Add (Current Prices) (BASE:2004-05)'},
    ('section3', 'table51', 'Base_2011-12'): {'TITLE': 'Gross Services Value Add (Current Prices) (BASE:2011-12)'},
    ('section3', 'table52', 'Base_2011-12'): {'TITLE': 'Gross Services Value Add (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table52', 'Base_2011-12'): {'TITLE': 'Gross Services Value Add (Constant Prices) (BASE:2011-12)'},
    ('section3', 'table53', 'Base_2011-12'): {'TITLE': 'Net Services Value Add (Current Prices) (BASE:2004-05)'},
    ('section3', 'table53', 'Base_2011-12'): {'TITLE': 'Net Services Value Add (Current Prices) (BASE:2011-12)'},
    ('section3', 'table54', 'Base_2011-12'): {'TITLE': 'Net Services Value Add (Constant Prices) (BASE:2004-05)'},
    ('section3', 'table54', 'Base_2011-12'): {'TITLE': 'Net Services Value Add (Constant Prices) (BASE:2011-12)'},
        }

state_synonyms = {
        'Andaman and Nicobar Islands': 'Andaman & Nicobar Islands',
        'Andhra Pradhesh': 'Andhra Pradesh',
        'NCT of Delhi': 'Delhi',
        'Jammu & Kashmir*': 'Jammu & Kashmir',
        'Jammu & Kashmir-U.T.': 'Jammu & Kashmir',
        'Jammu & Kashmir *': 'Jammu & Kashmir',
        }
