sections = {    'section1' : 'SOCIAL AND DEMOGRAPHIC INDICATORS',
                'section2' : 'HEALTH',
                'section3' : 'STATE DOMESTIC PRODUCT',
                'section4' : 'AGRICULTURE AND ALLIED',
                'section5' : 'ENVIRONMENT',
                'section6' : 'PRICE AND WAGES',
                'section7' : 'INDUSTRY',
                'section8' : 'INFRASTRUCTURE',
                'section9' : 'BANKING',
                'section10': 'FISCAL',
            }


group_names = {
    'SOCIAL AND DEMOGRAPHIC INDICATORS':
        [
            'Table 1: State-wise Total Population',
            'Table 2: State-wise Population in Rural Area',
            'Table 3: State-wise Population in Urban Area',
            'Table 4: State-wise Decadal Growth Rate of Population',
            'Table 5: State-wise Sex Ratio',
            'Table 6: State-wise Literacy Rate',
            'Table 7: State- wise Gross Enrolment Ratio',
            'Table 8: State-wise Density of Population',
            'Table 9: State-wise Birth Rate',
            'Table 10: State-wise Death Rate',
            'Table 11: State-wise Infant Mortality Rate',
            'Table 12: State-wise Maternal Mortality Ratio',
            'Table 13: State-wise Total Fertility Rate',
            'Table 14: State-wise Life Expectancy',
            'Table 15: State-wise Unemployment Rate: Usual Status (Adjusted) (Rural)',
            'Table 16: State-wise Unemployment Rate: Usual Status (Adjusted) (Urban)',
            'Table 17: State-wise Poverty Rate',
            'Table 18: State-wise Population Estimates- Multi-dimensional Poverty Index',
            'Table 19: State-wise Natural Population Growth Rate',
        ],
    'HEALTH':
        [
            'Table 20: State-wise Children Aged 6-59 Months Who are Anaemic',
            'Table 21: State-wise Pregnant Women Aged 15-49 Years Who are Anaemic',
            'Table 22: State-wise Health Infrastructure – Doctors and Specialists',
            'Table 23: State-wise Number of Government Hospitals',
            'Table 24: State-wise Public Expenditure on Health',
        ],
    'STATE DOMESTIC PRODUCT':
        [
            'Table 25: Per Capita Net State Domestic Product (Current Prices)',
            'Table 26: Per Capita Net State Domestic Product (Constant Prices)',
            'Table 27: Gross State Domestic Product (Current Prices)',
            'Table 28: Gross State Domestic Product (Constant Prices)',
            'Table 29: Net State Domestic Product (Current Prices)',
            'Table 30: Net State Domestic Product (Constant Prices)',
            'Table 31: Gross State Value Added by Economic Activity - Agriculture (Current Prices)',
            'Table 32: Gross State Value Added by Economic Activity - Agriculture (Constant Prices)',
            'Table 33: Net State Value Added by Economic Activity - Agriculture (Current Prices)',
            'Table 34: Net State Value Added by Economic Activity - Agriculture (Constant Prices)',
            'Table 35: Gross State Value Added by Economic Activity - Manufacturing (Current Prices)',
            'Table 36: Gross State Value Added by Economic Activity - Manufacturing (Constant Prices)',
            'Table 37: Net State Value Added by Economic Activity - Manufacturing (Current Prices)',
            'Table 38: Net State Value Added by Economic Activity - Manufacturing (Constant Prices)',
            'Table 39: Gross State Value Added by Economic Activity - Construction (Current Prices)',
            'Table 40: Gross State Value Added by Economic Activity - Construction (Constant Prices)',
            'Table 41: Net State Value Added by Economic Activity - Construction (Current Prices)',
            'Table 42: Net State Value Added by Economic Activity - Construction (Constant Prices)',
            'Table 43: Gross State Value Added by Economic Activity - Industry (Current Prices)',
            'Table 44: Gross State Value Added by Economic Activity - Industry (Constant Prices)',
            'Table 45: Net State Value Added by Economic Activity - Industry (Current Prices)',
            'Table 46: Net State Value Added by Economic Activity - Industry (Constant Prices)',
            'Table 47: Gross State Value Added by Economic Activity - Banking and Insurance (Current Prices)',
            'Table 48: Gross State Value Added by Economic Activity - Banking and Insurance (Constant Prices)',
            'Table 49: Net State Value Added by Economic Activity - Banking and Insurance (Current Prices)',
            'Table 50: Net State Value Added by Economic Activity - Banking and Insurance (Constant Prices)',
            'Table 51: Gross State Value Added by Economic Activity - Services (Current Prices)',
            'Table 52: Gross State Value Added by Economic Activity - Services (Constant Prices)',
            'Table 53: Net State Value Added by Economic Activity - Services (Current Prices)',
            'Table 54: Net State Value Added by Economic Activity - Services (Constant Prices)',
        ],
    'AGRICULTURE AND ALLIED':
        [
            'Table 55: State-wise Pattern of Land Use - Gross Sown Area',
            'Table 56: State-wise Pattern of Land Use- Net Sown Area',
            'Table 57: State-wise Pattern of Land Use - Gross Irrigated Area',
            'Table 58: State-wise Pattern of Land Use - Net Irrigated Area',
            'Table 59: State-wise Pattern of Land Use - Cropping Intensity',
            'Table 60: State-wise Production of Foodgrains - Rice',
            'Table 61: State-wise Production of Foodgrains - Wheat',
            'Table 62: State-wise Production of Foodgrains - Coarse Cereals',
            'Table 63: State-wise Production of Foodgrains - Pulses',
            'Table 64: State-wise Production of Total Foodgrains',
            'Table 65: State-wise Production of Non-Foodgrains - Oilseeds',
            'Table 66: State-wise Production of Non-Foodgrains - Cotton (Lintt)',
            'Table 67: State-wise Production of Non-Foodgrains - Sugarcane',
            'Table 68: State-wise Production of Non-Foodgrains - Raw Jute & Mesta',
            'Table 69: State-wise Area of Foodgrains - Rice',
            'Table 70: State-wise Area of Foodgrains - Wheat',
            'Table 71: State-wise Area of Foodgrains - Coarse Cereals',
            'Table 72: State-wise Area of Foodgrains - Pulses',
            'Table 73: State-wise Area of Total Foodgrains',
            'Table 74: State-wise Area of Total Fruits',
            'Table 75: State-wise Area of Total Vegetables',
            'Table 76: State-wise Production of Total Fruits',
            'Table 77: State-wise Production of Total Vegetables',
            'Table 78: State-wise Area of Non-Foodgrains - Oilseeds',
            'Table 79: State-wise Area of Non-Foodgrains - Cotton (Lintt)',
            'Table 80: State-wise Area of Non-Foodgrains - Sugarcane',
            'Table 81: State-wise Area of Non-Foodgrains - Raw Jute & Mesta',
            'Table 82: State-wise Estimates of Yield - Rice',
            'Table 83: State-wise Estimates of Yield - Wheat',
            'Table 84: State-wise Estimates of Yield - Coarse Cereals',
            'Table 85: State-wise Estimates of Yield - Pulses',
            'Table 86: State-wise Estimates of Yield - Total Foodgrains',
            'Table 87: State-wise Estimates of Yield - Oilseeds',
            'Table 88: State-wise Estimates of Yield - Cotton (Lintt)',
            'Table 89: State-wise Estimates of Yield - Sugarcane',
            'Table 90: State-wise Estimates of Yield - Raw Jute & Mesta',
            'Table 91: State-wise Per Hectare Consumption of Fertiliser (N+P+K)',
            'Table 92: State-wise Meat Production',
            'Table 93: State-wise Milk Production',
            'Table 94: State-wise Egg Production',
            'Table 95: State-wise Fish Production',
            'Table 96: State-wise Wool Production',
            'Table 97: State-wise RIDF Sanction and Disbursements',
            'Table 98: State-wise Storage Capacity of Foodgrains',
            'Table 99: Storage Capacity for Foodgrains and Utilisation under FCI',
            'Table 100: State-wise Cold Storage Capacity',
        ],
    'ENVIRONMENT':
        [
            'Table 101: State-wise Forest Cover',
            'Table 102: State-wise Tree Cover',
            'Table 103: Sub-Division-Wise Annual Rainfall',
            'Table 104: State-wise Expenditure on Relief on Natural Calamities',
            'Table 105: State-wise Sustainable Development Goals (SDGs) Score',
        ],
    'PRICE AND WAGES':
        [
            'Table 106: State-wise Average Inflation (CPI) - General',
            'Table 107: State-wise Average Inflation (CPI) - Food and Beverages',
            'Table 108: State-wise Average Inflation (CPI) - Fuel and Light',
            'Table 109: State-wise Average Inflation (CPI) - Housing (Urban)',
            'Table 110: State-wise Average Daily Wage Rates in Rural India (Men - Construction Workers)',
            'Table 111: State-wise Average Daily Wage Rates in Rural India (Men - General Agricultural Labourers)',
            'Table 112: State-wise Average Daily Wage Rates in Rural India (Men - Horticulture Workers)',
            'Table 113: State-wise Average Daily Wage Rates in Rural India (Men - Non-Agricultural Labourers)',
        ],
   'INDUSTRY':
       [
            'Table 114: State-wise Number of Factories',
            'Table 115: State-wise Fixed Capital',
            'Table 116: State-wise Working Capital',
            'Table 117: State-wise Physical Working Capital',
            'Table 118: State-wise Productive Capital',
            'Table 119: State-wise Invested Capital',
            'Table 120: State-wise Number of Workers',
            'Table 121: State-wise Total Persons Engaged',
            'Table 122: State-wise Total Emoluments',
            'Table 123: State-wise Total Input',
            'Table 124: State-wise Value of Gross Output',
            'Table 125: State-wise Net Value Added',
            'Table 126: State-wise Gross Value Added',
            'Table 127: State-wise Net Fixed Capital Formation',
            'Table 128: State-wise Gross Fixed Capital Formation',
            'Table 129: State-wise Gross Capital Formation',
            'Table 130: State-wise Number of Employees',
            'Table 131: State-wise Number of Mandays - Employees',
            'Table 132: State-wise Medium & Small Scale Industries - Total Number of Units',
            'Table 133: State-wise Medium & Small Scale Industries - Total Investments',
            'Table 134: State-wise Medium & Small Scale Industries - Total Production',
            'Table 135: State-wise Medium & Small Scale Industries - Total Employment',
        ],
   'INFRASTRUCTURE':
       [
            'Table 136: State-wise Per Capita Availability of Power',
            'Table 137: State-wise Availability of Power',
            'Table 138: State-wise Installed Capacity of Power',
            'Table 139: State-wise Power Requirement',
            'Table 140: State-wise Total Installed Capacity of Grid Interactive Renewable Power',
            'Table 141: State-wise Length of National Highways',
            'Table 142: State-wise Railway Route',
            'Table 143: State-wise Length of Roads',
            'Table 144: State-wise Length of State Highways',
            'Table 145: State-wise Ease of Doing Business Rank',
            'Table 146: State-wise Electricity Transmission & Distribution Losses',
            'Table 147: State-wise Telephones per 100 Population',
            'Table 148: State-wise Road Constructed under PMGSY',
        ],
   'BANKING':
       [
            'Table 149: State-wise Distribution of Offices of Scheduled Commercial Banks',
            'Table 150: State-wise Credit-Deposit Ratio of Scheduled Commercial Banks - According to Place of Sanction',
            'Table 151: State-wise Credit-Deposit Ratio of Scheduled Commercial Banks - According to Place of Utilisation',
            'Table 152: State-wise Deposits by Scheduled Commercial Banks in India',
            'Table 153: State-wise Credit by Scheduled Commercial Banks in India',
            'Table 154: State-wise Credit to Agriculture by Scheduled Commercial Banks',
            'Table 155: State-wise Credit to Industry by Scheduled Commercial Banks',
            'Table 156: State-wise Personal Loans by Scheduled Commercial Banks',
            'Table 157: State-wise Deposits of Regional Rural Banks',
            'Table 158: State-wise Credit of Regional Rural Banks',
            'Table 159: State-wise Credit-Deposit Ratio of Regional Rural Banks',
            'Table 160: State-wise Number of Branches of Regional Rural Banks',
        ],
   'FISCAL':
       [
            'Table 161: State-wise Gross Fiscal Deficit',
            'Table 162: State-wise Revenue Deficit',
            'Table 163: State-wise Primary Deficit',
            'Table 164: State-wise Own Tax Revenue',
            'Table 165: State-wise Own Non-Tax Revenue',
            'Table 166: State-wise Interest Payments',
            'Table 167: State-wise Pension',
            'Table 168: State-wise Capital Expenditure',
            'Table 169: State-wise Capital Outlay',
            'Table 170: State-wise Social Sector Expenditure',
            'Table 171: State-wise Composition of Outstanding Liabilities',
            'Table 172: State-wise Outstanding Guarantees of State Governments',
        ]
}

do_not_read = {'SOCIAL AND DEMOGRAPHIC INDICATORS' : ['Table 4:', 'Table 7:', 'Table 14:'],
        }
#TODO New format needed for 'SOCIAL AND DEMOGRAPHIC INDICATORS', 'Table 14:'

# 1960 - Bombay state split into Maharashtra and Gujarat
# 1963 - Nagaland carved out of Assam
# 1966 - Haryana and Himachal Pradesh carved out of Punjab state
# 1972 - Meghalaya , Manipur and Tripura were formed
# 1975 - Sikkim became part of Indian union
# 1987 - Goa and Arunachal Pradesh became states (earlier these were UTs)
# 2000 - Uttaranchal (out of UP), Jharkhand (out of Bihar) and Chhattisgarh (out of Madhya Pradesh) were formed
# Telangana (out of Andhra Pradesh), when it was eventually created in 2014, became India's 29th state.

state_change = {
        'Telangana' : 'Andhra Pradesh',
            }


state_synonyms = {
        'Andaman and Nicobar Islands' : 'Andaman & Nicobar Islands',
        'Andhra Pradhesh' : 'Andhra Pradesh',
        'NCT of Delhi'  : 'Delhi',
        }
